src/JoblandBundle/Entity/Blog/Post.php
<?php

namespace JoblandBundle\Entity\Blog;

/**
 * Post
 */
class Post
{
    /**
     * @var int
     */
    private $id;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
}

src/JoblandBundle/Form/RegistrationType.php
<?php


namespace JoblandBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;


class RegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('company');
        $builder->add('phoneNumber');
        $builder->add('nip');
        $builder->add('contactPerson');
        $builder->add('url');
        $builder->add('profilePictureFile', FileType::class);
        $builder->add('address');
        $builder->add('postalCode');
        $builder->add('city');
        $builder->add('countryId',CountryType::class);
        $builder->add('agreement', CheckboxType::class);
        $builder->add('rules', CheckboxType::class);
        
        
       
        
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getBlockPrefix()
    {
        return 'app_user_registration';
    }

    // For Symfony 2.x
    public function getName()
    {
        return $this->getBlockPrefix();
    }
} 

src/JoblandBundle/Controller/BlogController.php
<?php
namespace JoblandBundle\Controller;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints as Asset;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use JoblandBundle\Entity\Employer;
use JoblandBundle\Entity\Category;
use JoblandBundle\Entity\Country;
use JoblandBundle\Entity\Page;
use JoblandBundle\Form\Type\CreatePageType;
use JoblandBundle\Libs\Utils;
use JoblandBundle\Entity\News;
use JoblandBundle\Entity\Offer;
use JoblandBundle\Entity\Media;
use JoblandBundle\Entity\Portfolio;
use JoblandBundle\Entity\Partners;
use JoblandBundle\Entity\CvDatabase;
use JoblandBundle\Entity\Question;
use JoblandBundle\Entity\QuestionSubkind;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Security\Core\Security;
use JoblandBundle\Entity\Newsletter;
use Swift_Attachment;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Knp\Bundle\PaginatorBundle;
use Symfony\Component\HttpFoundation\Response;
use JoblandBundle\Entity\QuestionKind;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\Session\Session;




    
class BlogController extends Controller
{
	
	
	
	
	public function findByNot()
	{
		$qb = $this->createQueryBuilder('u');
		$qb->where('u.id != :identifier')
		->setParameter('identifier', 1);
	
		return $qb->getQuery()
		->getResult();
	}
	
	
// 	public function executeMenuTopAction() {


// 		$pages  = array(
// 			1 => array(
// 				'name' => 'O NAS',
// 				'url' => '/o-nas', 
// 				'child' => array(
// 					1 => array(
// 						'name' => 'Ogólne informacje',
// 						'url' => '/o-nas' 
// 					),
// 					2 => array(
// 						'name' => 'Media',
// 						'url' => '/media' 
// 					),
// 					3 => array(
// 						'name' => 'Portfolio i referencje',
// 						'url' => '/portfolio' 
// 					),

// 					4 => array(
// 						'name' => 'Partnerzy',
// 						'url' => '/partnerzy' 
// 					),
// 				)
// 			),
// 				2 => array(
// 				'name' => 'Dla pracodawców',
// 				'url' => '/jak-dzialamy', 
// 				'child' => array(
// 					1 => array(
// 						'name' => 'Jak działamy',
// 						'url' => '/jak-dzialamy' 
// 					),
// 					2 => array(
// 						'name' => 'Zamieszczanie ofert pracy',
// 						'url' => '/zamieszczanie-ofert' 
// 					),
// 					3 => array(
// 						'name' => 'Newsletter',
// 						'url' => '/newsletter' 
// 					),

// 					4 => array(
// 						'name' => 'Branża budownictwa budowlanego',
// 						'url' => '/branza' 
// 					),
// 				)
// 			),
// 				3 => array(
// 				'name' => 'Dla kandytatów',
// 				'url' => '/jak-dziala', 
// 				'child' => array(
// 					1 => array(
// 						'name' => 'Jak działa Jobland.pl',
// 						'url' => '/jak-dziala' 
// 					),
// 					2 => array(
// 						'name' => 'Oferty pracy',
// 						'url' => '/oferty-pracy' 
// 					),
// 					3 => array(
// 						'name' => 'FAQ dla wyjeżdzających',
// 						'url' => '/faq' 
// 					),

// 					4 => array(
// 						'name' => 'Porady i Wskazówki',
// 						'url' => '/porady-wskazowki' 
// 					),
// 				)
// 			),

// 				4 => array(
// 				'name' => 'Forum',
// 				'url' => '/forum',
				
// 				),	
// 				5 => array(
// 				'name' => 'Kontakt',
// 				'url' => '/kontakt',
				
// 				),	
// 		);
// 	return $this->render('JoblandBundle:Blog:menuTop.html.twig', array(
// 			'pages' => $pages
// 		));	
// 	}
	
	
	
	/**
     * @Route("/footer")
     *
     */
	public function footerAction() {
		
		}
		
		
		/**
		 * @Route("/", name="homepage")
		 *
		 */
		public function IndexAction(Request $request) {
			
			
		$Repo = $this->getDoctrine()->getRepository('JoblandBundle:Offer');
			
		$rows = $Repo ->findAll();
		$pl = $Repo ->findByCountryId('PL');
		$Repo = $this->getDoctrine()->getRepository('JoblandBundle:News');
			
		$news = $Repo ->findAll();
		
		return $this->render('JoblandBundle:Blog:index.html.twig', array(
			
				'rows' => $rows,
				'news' => $news,
				'pl' => $pl
		));
		}
			
		
		/**
		 * @Route("/admin/admin-panel")
		 *
		 */
		public function AdminPanelAction() {
			return $this->render('JoblandBundle:Blog:admin/admin-panel.html.twig', array());
		}
	
		/**
		 * @Route("/admin/about-us", name="admin-about-us")
		 *
		 */
		public function AdminAboutUsAction(Request $request) {
			
			
			$media = new Media;
			
			$mediaform = $this->createFormBuilder($media)
			->add('title', TextType::class, array(
					'label' => 'Tytuł'))
			->add('date', TextType::class, array(
							'label' => 'Date'
							
							)
							
			)
			->add('content', TextAreaType::class, array(
									'label' => 'Treść',
									'attr' => array('class' => 'ckeditor')
			))
			->add('url', TextType::class, array(
											'label' => 'Adres url'))
			->add('dodaj', SubmitType::class)
							->getForm();
							$mediaform->handleRequest($request);
								
			
							if($mediaform->isValid()){
			
								
								
								$title = $mediaform['title']->getData();
								$content = $mediaform['content']->getData();
								$date = $mediaform['date']->getData();
								$url = $mediaform['url']->getData();
								
								$timestamp = strtotime($date);
								$date = date('Y-m-d',$timestamp );
								
							
							
								
								
								
							
								$status = 1;
									
								$media->setContent($content);
								$media->setTitle($title);
								$media->setStatus($status);
								$media->setDate($date);
								$media->setUrl($url);
			
								$em = $this->getDoctrine()->getManager();
								$em->persist($media);
								$em->flush();
			
								return $this->redirectToRoute('admin-about-us');
							}
			
			
			
							$Repo = $this->getDoctrine()->getRepository('JoblandBundle:Media');
							$mediarows = $Repo ->findAll();
							
							$partners = new Partners;
								
							$partnersform = $this->createFormBuilder($partners)
							->add('name', TextType::class, array(
									'label' => 'Tytuł'))
									
											
							->add('text', TextAreaType::class, array(
													'label' => 'Treść',
													'attr' => array('class' => 'ckeditor')
											))
							->add('link', TextType::class, array(
													'label' => 'Link',
													
											))
							->add('logourl', FileType::class, array(
													'label' => 'Dodaj Logo'))
													->add('dodaj', SubmitType::class)
													->getForm();
							$partnersform->handleRequest($request);
							
														
									if($partnersform->isValid()){
															
										$savePath = $this->get('kernel')->getRootDir().'/../web/uploads/partners/';
										
										$formData = $partnersform->getData();
										
										$randVal = rand(1000,9999);
										
											
										$file = $partnersform->get('logourl')->getData();
										if(NULL !=$file){
											$newName = sprintf('img__%d.%s', $randVal, $file->guessExtension());
											$file->move($savePath, $newName);}
											
							
														$name = $partnersform['name']->getData();
														$text = $partnersform['text']->getData();
														$link = $partnersform['link']->getData();
														$logourl = '/web/uploads/partners/'.$newName;
													
															
															
							
							
							
															
													
															
														$partners->setName($name);
														$partners->setText($text);
														$partners->setLogoUrl($logourl);
												
															
														$em = $this->getDoctrine()->getManager();
														$em->persist($partners);
														$em->flush();
															
														return $this->redirectToRoute('admin-about-us');
													}
														
														
														
													$Repo = $this->getDoctrine()->getRepository('JoblandBundle:Partners');
													$partnersrows = $Repo ->findAll();
			
							
								
							$portfolioform = $this->createFormBuilder()
							->add('name', TextType::class, array(
									'label' => 'Tytuł'))
							->add('city', TextType::class, array(
											'label' => 'Miasto'))
							
							->add('countryid', CountryType::class, array(
													'label' => 'Kraj'))
							->add('year', TextType::class, array(
															'label' => 'Rok'))
							->add('imageurl', FileType::class, array(
													'label' => 'Obrazek'))
							->add('header', TextareaType::class, array(
													'label' => 'Nagłówek',
													'attr' => array('class' => 'ckeditor')
											))
							->add('content', TextareaType::class, array(
													'label' => 'Treść',	
													'attr' => array('class' => 'ckeditor')
											))

src/JoblandBundle/Resources/views/Blog/admin/addPage.html.twig
{% extends 'JoblandBundle:Blog:admin/layout-admin.html.twig' %}
{% block bodyClasses %}form-page{% endblock %}
{% block content %}
{{ form_start(form) }}
    {{ form_errors(form) }}
    <div class="admin-panel">
    	<div class="add-page">
        {% if register is defined %}
        <div class="col-lg-12">
            <a href="{{ path('showPage', {'slug': register.megaSlug}) }}" target="_blank">Zobacz stronę</a>            
        </div>
        {% endif %}
        <div class="col-lg-8">    
            <div class="widget-container">
                <div class="widget-header">
                    <h3><i class="icon-list-alt"></i> PODSTAWOWE INFORMACJE</h3>
                    <i class="icon-chevron-down hide-widget"></i>
                </div>
                
                <div class="widget-content">
                    <div>
                        <fieldset>
                            <div class="control-group">
                                <label class="col-sm-3 control-label">
                                    {{ form_label(form.name) }}
                                </label>
                                <div class="col-sm-9">
                                    {{ form_errors(form.name) }}
                                    {{ form_widget(form.name) }}
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="col-sm-3 control-label">
                                    {{ form_label(form.nameMenu) }}
                                </label>
                                <div class="col-sm-9">
                                    {{ form_errors(form.nameMenu) }}
                                    {{ form_widget(form.nameMenu) }}
                                </div>
                            </div>
                             <div class="control-group">
                                <label class="col-sm-3 control-label">
                                    {{ form_label(form.language) }}
                                </label>
                                <div class="col-sm-9">
                                    {{ form_errors(form.language) }}
                                    {{ form_widget(form.language) }}
                                </div>
                            </div>
                          
                            <div class="control-group">
                                <label class="col-sm-3 control-label">
                                    {{ form_label(form.externalUrl) }}
                                </label>
                                <div class="col-sm-9">
                                    {{ form_errors(form.externalUrl) }}
                                    {{ form_widget(form.externalUrl) }}
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="control-label col-sm-3">
                                    {{ form_label(form.content) }}
                                </label>
                                <div class="controls form-group col-sm-9">
                                    {{ form_errors(form.content) }}
                                    {{ form_widget(form.content) }}
                                </div>
                            </div>
                       </fieldset>
                    </div>
                </div>
            </div>
            
            <div class="widget-container">
                <div class="widget-header">
                    
                    <h3><i class="icon-list-alt"></i> SEO</h3>
                    <i class="icon-chevron-down hide-widget"></i>
                </div>
                
                <div class="widget-content">
                    <div>
                        <fieldset>
                            <div class="control-group">
                                <label class="col-sm-3 control-label">
                                    Meta Title
                                </label>
                                <div class="col-sm-9">
                                    <input type="text" id="create_page_metaTitle" name="create_page[option][metaTitle]" value="{{ register.getOption('metaTitle') is defined ? register.getOption('metaTitle') : '' }}">
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="col-sm-3 control-label">
                                    Meta Description
                                </label>
                                <div class="col-sm-9">
                                    <input type="text" id="create_page_metaTitle" name="create_page[option][metaDescription]" value="{{ register.getOption('metaDescription') is defined ? register.getOption('metaDescription') : '' }}">
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="col-sm-3 control-label">
                                    Meta Keywords
                                </label>
                                <div class="col-sm-9">
                                    <input type="text" id="create_page_metaTitle" name="create_page[option][metaKeywords]" value="{{ register.getOption('metaKeywords') is defined ? register.getOption('metaKeywords') : '' }}">
                                </div>
                            </div>
                       </fieldset>
                    </div>
                </div>
            </div>
            {# 
            <div class="import-custom-forms">
                {% if register is defined and register.kind != 0 %}
                    
                        {{ include('AppBundle:Admin:template'~register.kind~'Form.html.twig')}}
                    
                {% endif %}
            </div>
            #}
        </div>  
        <div class="col-lg-4">
            <div class="widget-container">
                <div class="widget-header">
                    <h3><i class="icon-list-alt"></i> AKCJE</h3>
                    <i class="icon-chevron-down hide-widget"></i>
                </div>
                <div class="widget-content">
                    <div>
                        <fieldset>
                            <div class="control-group">
                                <label class="col-sm-6 control-label">Data utworzenia</label>
                                <div class="col-sm-6 form-group">
                                     <div class="form-group">
                                        <div class='input-group date' id='datetimepicker1'>
                                            <input>
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                       </fieldset>
                    </div>
                    <div class="text-center">
                            {{ form_widget(form.save) }}
                    </div>
                </div>
            </div>
        
            
            <div class="widget-container">
                <div class="widget-header">
                    
                    <h3>DODATKOWE INFORMACJE</h3>
                    <i class="icon-chevron-down hide-widget"></i>
                </div>
                <div class="widget-content">
                    <div class="">
                        <fieldset>
                            <div class="control-group">
                               <label class="control-label col-sm-5">
                                    {{ form_label(form.parent) }}
                                </label>
                                <div class="controls form-group col-sm-7">
                                    {{ form_errors(form.parent) }}
                                    {{ form_widget(form.parent) }}
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="col-sm-5 control-label">
                                    {{ form_label(form.isPublished) }}
                                </label>
                                <div class="col-sm-7">
                                    {{ form_errors(form.isPublished) }}
                                    {{ form_widget(form.isPublished) }}
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="col-sm-5 control-label">
                                    {{ form_label(form.isFeatured) }}
                                </label>
                                <div class="col-sm-7">
                                    {{ form_errors(form.isFeatured) }}
                                    {{ form_widget(form.isFeatured) }}
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="col-sm-5 control-label">{{ form_label(form.kind) }}</label>
                                <div class="col-sm-7">
                                    {{ form_errors(form.kind) }}
                                    {{ form_widget(form.kind) }}
                                </div>
                            </div>
                       </fieldset>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
{{ form_end(form) }}


{% endblock content %}
{#

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function() {
            {% if register.id is defined %}
                pageId = {{ register.id }};
            {% else %}
                pageId = 0;
            {% endif %}
            
            $('#create_page_kind').change(function() {
                val = $(this).val();
                $.post( "{{path('pageCustomField')}}", { id: val, pageId: pageId} ).done(function( data ) {
                    $('.import-custom-forms').html(data);
                }); 
            });
        });
        
    </script>
{% endblock %}
 #}

src/JoblandBundle/Resources/views/Blog/admin/admin-about-us.html.twig
{# Panel Administracyjny #}
{% extends 'JoblandBundle:Blog:admin/layout-admin.html.twig' %}

{% block title %}News{% endblock %}


{% block content %}
<div class="tabs-wrapper">
									<ul>
										<li class="active">
											<a href="/web/app_dev.php/admin/about-us" data-id="1">Media</a>
										</li>
										<li>
											<a href="/web/app_dev.php/admin/about-us" data-id="2">Portfolio</a>
										</li>
										<li>
											<a href="/web/app_dev.php/admin/about-us" data-id="3">Partnerzy</a>
										</li>
										</ul>
										</div>
<div class="tabs-content-wrapper">
<div class="tabs-content">									
<div class="tab tab-external active" id="tab-1">					

<div class="admin-wrapper">
<div class="admin-panel" id="news-admin">
	
	<table id="first-table">
	<tr>
		<th>ID</th>
		<th>Tytuł</th>
		<th>Status</th>
		<th>Data Publikacji</th>
		<th>URL</th>
		<th>Opcje Aktualności</th>
		
		
		
	</tr>
	</table>
	{% for entry in mediarows %}
	<table>
	<tr>
		<th>{{ entry.id}}</th>
		<th>{{ entry.title}}</th>
		{%   if entry.status == 1 %}<th>Opublikowany</th>
		{% else %}
		<th>Niepublikowany</th>
		{% endif %}
		
		<th>{{ entry.date | date('l, F j, Y')}}</th>
		<th>{{ entry.url}}</th>
		<th><a href="/admin/edit-media/{{ entry.id}}" class="button">Edytuj</button><a  href="/admin/delete-news/{{ entry.id}}" class="main-button-red">Usuń</a></th>
		
	</tr>
	</table>
		
	
	
	{% else %}
	
									
									<h2> Brak Mediów </h2>
									
									{% endfor %}


</div>
	
<div class="add-news">
{{form_start(mediaform)}}
{{form_widget(mediaform)}}
{{form_end(mediaform)}}
</div>
</div>
</div>
<div class="tab tab-external" id="tab-2">
<div class="admin-panel" id="news-admin">
<table id="first-table">
	<tr>
		<th>ID</th>
		<th>Tytuł</th>
		<th>Miasto</th>
		<th>Kraj</th>
		<th>Rok</th>
		<th>Opcje</th>
		
		
		
		
	</tr>
	</table>
	{% for entry in portfoliorows %}
	<table>
	<tr>
		<th>{{ entry.id}}</th>
		<th>{{ entry.name}}</th>
		<th>{{ entry.city}}</th>
		<th>{{ entry.countryid}}</th>
		<th>{{ entry.year }}</th>
		
		
		<th><a href="/admin/edit-portfolio/{{ entry.id}}" class="button">Edytuj</button><a  href="/admin/delete-portfolio/{{ entry.id}}" class="main-button-red">Usuń</a></th>
		
	</tr>
	</table>
		
	
	
	{% else %}
	
									
									<h2> Brak Portfolio </h2>
									
									{% endfor %}


</div>
	
<div class="add-news">
{{form_start(portfolioform)}}
{{form_widget(portfolioform)}}
{{form_end(portfolioform)}}
</div>
</div>
<div class="tab tab-external" id="tab-3">
<div class="admin-panel" id="news-admin">
<table id="first-table">
	<tr>
		<th>ID</th>
		<th>Partner</th>
		<th>Link</th>
		<th>Logo url</th>
		<th>Opcje</th>
		
		
		
		
	</tr>
	</table>
	{% for entry in partnersrows %}
	<table>
	<tr>
		<th>{{ entry.id}}</th>
		<th>{{ entry.name}}</th>
		<th>{{ entry.link}}</th>
		<th>{{ entry.logourl}}</th>
		
		
		<th><a href="/admin/edit-partners/{{ entry.id}}" class="button">Edytuj</button><a  href="/admin/delete-partners/{{ entry.id}}" class="main-button-red">Usuń</a></th>
		
	</tr>
	</table>
		
	
	
	{% else %}
	
									
									<h2> Brak Partnerów </h2>
									
									{% endfor %}


</div>
<div class="add-news">
{{form_start(partnersform)}}
{{form_widget(partnersform)}}
{{form_end(partnersform)}}
</div>
</div>
</div>
</div>
 <script>
  $( function() {
    $( "#form_date" ).datepicker();
    
  } );
  </script>
{% endblock %}

src/JoblandBundle/Resources/views/Blog/admin/admin-employers.html.twig
{# Panel Administracyjny #}
{% extends 'JoblandBundle:Blog:admin/layout-admin.html.twig' %}

{% block title %}Pracodawcy{% endblock %}


{% block content %}

<div class="admin-panel">
	
	<table id="first-table">
	<tr>
		<th>ID</th>
		<th>Pracodawca</th>
		<th>NIP</th>
		<th>Miasto</th>
		<th class=email-admin">Email</th>
		<th>Osoba kontaktowa</th>
		<th>Nr telefonu</th>
		<th>Opcje Użytkowników</th>
		
	</tr>
	</table>
	{% for entry in rows %}
	<table>
	<tr>
		<th>{{ entry.id}}</th>
		<th>{{ entry.company}}</th>
		<th>{{ entry.nip}}</th>
		<th>{{ entry.city}}</th>
		<th class=email-admin">{{ entry.email }}</th>
		<th>{{ entry.contactperson}}</th>
		<th>{{ entry.phonenumber}}</th>
		<th><a href="/admin/edit-employer/{{ entry.id}}" class="button">Edytuj</a><a href="/admin/delete-employer/{{ entry.id}}" class="main-button-red">Usuń</a></th>
		
	</tr>
	</table>
		
	
	
	{% else %}
	
									
									<h2> Brak ofert Pracy </h2>
									
									{% endfor %}
</div>

				
{% endblock %}

src/JoblandBundle/Resources/views/Blog/admin/admin-news.html.twig
{# Panel Administracyjny #}
{% extends 'JoblandBundle:Blog:admin/layout-admin.html.twig' %}

{% block title %}News{% endblock %}


{% block content %}
<div class="admin-panel" id="news-admin">
	
	<table id="first-table">
	<tr>
		<th>ID</th>
		<th>Tytuł</th>
		<th>Status</th>
		<th>Data Publikacji</th>
		<th>Opcje Aktualności</th>
		
		
		
	</tr>
	</table>
	{% for entry in rows %}
	<table>
	<tr>
		<th>{{ entry.id}}</th>
		<th>{{ entry.title}}</th>
		{%   if entry.status == 1 %}<th>Główny</th>
		{% elseif entry.status == 2 %}<th>Inne</th>
		{% elseif entry.status == 3 %}<th>Nieaktywny</th>
		{% endif %}
		<th>{{ entry.date | date('l, F j, Y')}}</th>
		<th><a href="/admin/edit-news/{{ entry.id}}" class="button">Edytuj</button><a href="/admin/delete-news/{{ entry.id}}" class="main-button-red">Usuń</a></th>
		
	</tr>
	</table>
		
	
	
	{% else %}
	
									
									<h2> Brak Aktualności </h2>
									
									{% endfor %}


</div>
<div class="add-news">
{{form_start(form)}}
{{form_widget(form)}}
{{form_end(form)}}
</div>
<script>
  $( function() {
    $( "#form_date" ).datepicker();
  } );
  </script>
{% endblock %}

src/JoblandBundle/Resources/views/Blog/admin/admin-newsletter.html.twig
{# Panel Administracyjny #}
{% extends 'JoblandBundle:Blog:admin/layout-admin.html.twig' %}

{% block title %}Newsletter{% endblock %}


{% block content %}

<div class="admin-panel"  id="newsletter-admin">
	  
	<table id="first-table">
	<tr>
		<th>ID</th>
		<th class="email-admin">Email</th>
		<th>Status</th>
		<th>Opcje Newslettera</th>
		
		
	</tr>
	</table>
	{% for entry in rows %}
	<table>
	<tr>
		<th>{{ entry.id}}</th>
		<th class="email-admin">{{ entry.email}}</th>
		<th>
{% if entry.status == 1 %}
<a href="inactive-newsletter/{{ entry.id}}" class="admin-active">Aktywny</a>
{% else %}
<a href="active-newsletter/{{ entry.id}}" class="admin-inactive">Nieaktywny</a>
{% endif %}</th>
		<th><a href="/admin/edit-newsletter/{{ entry.id}}" class="button">Edytuj</button><a href="/admin/delete-newsletter/{{ entry.id}}" class="main-button-red">Usuń</a></th>
		
	</tr>
	</table>
		
	
	
	{% else %}
	
									
									<h2> Brak osób zapisanych w Newsletterze </h2>
									
		
									{% endfor %}
              

</div>
<div class="add-newsletter">
                    {{form_start(form)}}
                    {{form_widget(form)}}
                    {{form_end(form)}}
                </div>

{% endblock %}